<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Product\Types;

/**
 *
 * @property string $invocationId
 * @property string $categoryId
 * @property string $keywords
 * @property \DTS\eBaySDK\Product\Types\PropertyValue[] $propertyFilter
 * @property \DTS\eBaySDK\Product\Types\SortOrder $sortOrder
 * @property string[] $dataset
 * @property string[] $datasetPropertyName
 * @property \DTS\eBaySDK\Product\Types\PaginationInput $paginationInput
 * @property \DTS\eBaySDK\Product\Types\ProductStatus $productStatusFilter
 */
class ProductRequest extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'invocationId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'invocationId'
        ],
        'categoryId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'categoryId'
        ],
        'keywords' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'keywords'
        ],
        'propertyFilter' => [
            'type' => \DTS\eBaySDK\Product\Types\PropertyValue::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'propertyFilter'
        ],
        'sortOrder' => [
            'type' => \DTS\eBaySDK\Product\Types\SortOrder::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'sortOrder'
        ],
        'dataset' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'dataset'
        ],
        'datasetPropertyName' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'datasetPropertyName'
        ],
        'paginationInput' => [
            'type' => \DTS\eBaySDK\Product\Types\PaginationInput::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paginationInput'
        ],
        'productStatusFilter' => [
            'type' => \DTS\eBaySDK\Product\Types\ProductStatus::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'productStatusFilter'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
