<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Product\Types;

/**
 *
 * @property \DTS\eBaySDK\Product\Types\StringValue $text
 * @property \DTS\eBaySDK\Product\Types\NumericValue $number
 * @property \DTS\eBaySDK\Product\Types\URIValue $URL
 */
class Value extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'text' => [
            'type' => \DTS\eBaySDK\Product\Types\StringValue::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'text'
        ],
        'number' => [
            'type' => \DTS\eBaySDK\Product\Types\NumericValue::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'number'
        ],
        'URL' => [
            'type' => \DTS\eBaySDK\Product\Types\URIValue::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'URL'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
