<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Taxonomy\Types;

/**
 *
 * @property \DTS\eBaySDK\Taxonomy\Types\AspectConstraint $aspectConstraint
 * @property \DTS\eBaySDK\Taxonomy\Types\AspectValue[] $aspectValues
 * @property string $localizedAspectName
 */
class Aspect extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'aspectConstraint' => [
            'type' => \DTS\eBaySDK\Taxonomy\Types\AspectConstraint::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'aspectConstraint'
        ],
        'aspectValues' => [
            'type' => \DTS\eBaySDK\Taxonomy\Types\AspectValue::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'aspectValues'
        ],
        'localizedAspectName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'localizedAspectName'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        $this->setValues(self::class, $childValues);
    }
}
