<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Enums\AccountDetailEntryCodeType $AccountDetailsEntryType
 * @property string $Description
 * @property \DTS\eBaySDK\Trading\Types\AmountType $Balance
 * @property \DateTime $Date
 * @property \DTS\eBaySDK\Trading\Types\AmountType $GrossDetailAmount
 * @property string $ItemID
 * @property string $Memo
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ConversionRate
 * @property \DTS\eBaySDK\Trading\Types\AmountType $NetDetailAmount
 * @property string $RefNumber
 * @property integer $VATPercent
 * @property string $Title
 * @property string $OrderLineItemID
 * @property string $TransactionID
 * @property boolean $ReceivedTopRatedDiscount
 */
class AccountEntryType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'AccountDetailsEntryType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AccountDetailsEntryType'
        ],
        'Description' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Description'
        ],
        'Balance' => [
            'type' => \DTS\eBaySDK\Trading\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Balance'
        ],
        'Date' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Date'
        ],
        'GrossDetailAmount' => [
            'type' => \DTS\eBaySDK\Trading\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GrossDetailAmount'
        ],
        'ItemID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemID'
        ],
        'Memo' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Memo'
        ],
        'ConversionRate' => [
            'type' => \DTS\eBaySDK\Trading\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConversionRate'
        ],
        'NetDetailAmount' => [
            'type' => \DTS\eBaySDK\Trading\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'NetDetailAmount'
        ],
        'RefNumber' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RefNumber'
        ],
        'VATPercent' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VATPercent'
        ],
        'Title' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Title'
        ],
        'OrderLineItemID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'OrderLineItemID'
        ],
        'TransactionID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TransactionID'
        ],
        'ReceivedTopRatedDiscount' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReceivedTopRatedDiscount'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
