<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Types\ListingDurationDefinitionsType $ListingDurations
 * @property \DTS\eBaySDK\Trading\Types\ShippingTermRequiredDefinitionType $ShippingTermsRequired
 * @property \DTS\eBaySDK\Trading\Types\BestOfferEnabledDefinitionType $BestOfferEnabled
 * @property \DTS\eBaySDK\Trading\Types\HomePageFeaturedEnabledDefinitionType $HomePageFeaturedEnabled
 * @property \DTS\eBaySDK\Trading\Types\ProPackEnabledDefinitionType $ProPackEnabled
 * @property \DTS\eBaySDK\Trading\Types\ValuePackEnabledDefinitionType $ValuePackEnabled
 * @property \DTS\eBaySDK\Trading\Types\ProPackPlusEnabledDefinitionType $ProPackPlusEnabled
 * @property \DTS\eBaySDK\Trading\Types\AdFormatEnabledDefinitionType $AdFormatEnabled
 * @property \DTS\eBaySDK\Trading\Types\BestOfferCounterEnabledDefinitionType $BestOfferCounterEnabled
 * @property \DTS\eBaySDK\Trading\Types\BestOfferAutoDeclineEnabledDefinitionType $BestOfferAutoDeclineEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketSpecialitySubscriptionDefinitionType $LocalMarketSpecialitySubscription
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketRegularSubscriptionDefinitionType $LocalMarketRegularSubscription
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketPremiumSubscriptionDefinitionType $LocalMarketPremiumSubscription
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketNonSubscriptionDefinitionType $LocalMarketNonSubscription
 * @property \DTS\eBaySDK\Trading\Types\MinimumReservePriceDefinitionType $MinimumReservePrice
 * @property \DTS\eBaySDK\Trading\Types\TCREnabledDefinitionType $TransactionConfirmationRequestEnabled
 * @property \DTS\eBaySDK\Trading\Types\SellerContactDetailsEnabledDefinitionType $SellerContactDetailsEnabled
 * @property \DTS\eBaySDK\Trading\Types\SkypeMeTransactionalEnabledDefinitionType $SkypeMeTransactionalEnabled
 * @property \DTS\eBaySDK\Trading\Types\SkypeMeNonTransactionalEnabledDefinitionType $SkypeMeNonTransactionalEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalListingDistancesRegularDefinitionType $LocalListingDistancesRegular
 * @property \DTS\eBaySDK\Trading\Types\LocalListingDistancesSpecialtyDefinitionType $LocalListingDistancesSpecialty
 * @property \DTS\eBaySDK\Trading\Types\LocalListingDistancesNonSubscriptionDefinitionType $LocalListingDistancesNonSubscription
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdPaymentMethodEnabledDefinitionType $ClassifiedAdPaymentMethodEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdShippingMethodEnabledDefinitionType $ClassifiedAdShippingMethodEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdBestOfferEnabledDefinitionType $ClassifiedAdBestOfferEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdCounterOfferEnabledDefinitionType $ClassifiedAdCounterOfferEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdAutoDeclineEnabledDefinitionType $ClassifiedAdAutoDeclineEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdContactByPhoneEnabledDefinitionType $ClassifiedAdContactByPhoneEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdContactByEmailEnabledDefintionType $ClassifiedAdContactByEmailEnabled
 * @property \DTS\eBaySDK\Trading\Types\SafePaymentRequiredDefinitionType $SafePaymentRequired
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdPayPerLeadEnabledDefinitionType $ClassifiedAdPayPerLeadEnabled
 * @property \DTS\eBaySDK\Trading\Types\ItemSpecificsEnabledDefinitionType $ItemSpecificsEnabled
 * @property \DTS\eBaySDK\Trading\Types\PaisaPayFullEscrowEnabledDefinitionType $PaisaPayFullEscrowEnabled
 * @property \DTS\eBaySDK\Trading\Types\BrandMPNIdentifierEnabledDefinitionType $BrandMPNIdentifierEnabled
 * @property \DTS\eBaySDK\Trading\Types\BestOfferAutoAcceptEnabledDefinitionType $BestOfferAutoAcceptEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdAutoAcceptEnabledDefinitionType $ClassifiedAdAutoAcceptEnabled
 * @property \DTS\eBaySDK\Trading\Types\CrossBorderTradeNorthAmericaEnabledDefinitionType $CrossBorderTradeNorthAmericaEnabled
 * @property \DTS\eBaySDK\Trading\Types\CrossBorderTradeGBEnabledDefinitionType $CrossBorderTradeGBEnabled
 * @property \DTS\eBaySDK\Trading\Types\CrossBorderTradeAustraliaEnabledDefinitionType $CrossBorderTradeAustraliaEnabled
 * @property \DTS\eBaySDK\Trading\Types\PayPalBuyerProtectionEnabledDefinitionType $PayPalBuyerProtectionEnabled
 * @property \DTS\eBaySDK\Trading\Types\BuyerGuaranteeEnabledDefinitionType $BuyerGuaranteeEnabled
 * @property \DTS\eBaySDK\Trading\Types\ListingEnhancementDurationDefinitionType $GalleryFeaturedDurations
 * @property \DTS\eBaySDK\Trading\Types\INEscrowWorkflowTimelineDefinitionType $INEscrowWorkflowTimeline
 * @property \DTS\eBaySDK\Trading\Types\PayPalRequiredDefinitionType $PayPalRequired
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProAdFormatEnabledDefinitionType $eBayMotorsProAdFormatEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProContactByPhoneEnabledDefinitionType $eBayMotorsProContactByPhoneEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProPhoneCountDefinitionType $eBayMotorsProPhoneCount
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProContactByAddressEnabledDefinitionType $eBayMotorsProContactByAddressEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProStreetCountDefinitionType $eBayMotorsProStreetCount
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProCompanyNameEnabledDefinitionType $eBayMotorsProCompanyNameEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProContactByEmailEnabledDefinitionType $eBayMotorsProContactByEmailEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProBestOfferEnabledDefinitionType $eBayMotorsProBestOfferEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProAutoAcceptEnabledDefinitionType $eBayMotorsProAutoAcceptEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProAutoDeclineEnabledDefinitionType $eBayMotorsProAutoDeclineEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProPaymentMethodCheckOutEnabledDefinitionType $eBayMotorsProPaymentMethodCheckOutEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProShippingMethodEnabledDefinitionType $eBayMotorsProShippingMethodEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProCounterOfferEnabledDefinitionType $eBayMotorsProCounterOfferEnabled
 * @property \DTS\eBaySDK\Trading\Types\EBayMotorsProSellerContactDetailsEnabledDefinitionType $eBayMotorsProSellerContactDetailsEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketAdFormatEnabledDefinitionType $LocalMarketAdFormatEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketContactByPhoneEnabledDefinitionType $LocalMarketContactByPhoneEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketPhoneCountDefinitionType $LocalMarketPhoneCount
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketContactByAddressEnabledDefinitionType $LocalMarketContactByAddressEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketStreetCountDefinitionType $LocalMarketStreetCount
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketCompanyNameEnabledDefinitionType $LocalMarketCompanyNameEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketContactByEmailEnabledDefinitionType $LocalMarketContactByEmailEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketBestOfferEnabledDefinitionType $LocalMarketBestOfferEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketAutoAcceptEnabledDefinitionType $LocalMarketAutoAcceptEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketAutoDeclineEnabledDefinitionType $LocalMarketAutoDeclineEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketPaymentMethodCheckOutEnabledDefinitionType $LocalMarketPaymentMethodCheckOutEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketShippingMethodEnabledDefinitionType $LocalMarketShippingMethodEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketCounterOfferEnabledDefinitionType $LocalMarketCounterOfferEnabled
 * @property \DTS\eBaySDK\Trading\Types\LocalMarketSellerContactDetailsEnabledDefinitionType $LocalMarketSellerContactDetailsEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdPhoneCountDefinitionType $ClassifiedAdPhoneCount
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdContactByAddressEnabledDefinitionType $ClassifiedAdContactByAddressEnabled
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdStreetCountDefinitionType $ClassifiedAdStreetCount
 * @property \DTS\eBaySDK\Trading\Types\ClassifiedAdCompanyNameEnabledDefinitionType $ClassifiedAdCompanyNameEnabled
 * @property \DTS\eBaySDK\Trading\Types\SpecialitySubscriptionDefinitionType $SpecialitySubscription
 * @property \DTS\eBaySDK\Trading\Types\RegularSubscriptionDefinitionType $RegularSubscription
 * @property \DTS\eBaySDK\Trading\Types\PremiumSubscriptionDefinitionType $PremiumSubscription
 * @property \DTS\eBaySDK\Trading\Types\NonSubscriptionDefinitionType $NonSubscription
 * @property \DTS\eBaySDK\Trading\Types\ReturnPolicyEnabledDefinitionType $ReturnPolicyEnabled
 * @property \DTS\eBaySDK\Trading\Types\HandlingTimeEnabledDefinitionType $HandlingTimeEnabled
 * @property \DTS\eBaySDK\Trading\Types\ReviseQuantityAllowedDefinitionType $ReviseQuantityAllowed
 * @property \DTS\eBaySDK\Trading\Types\RevisePriceAllowedDefinitionType $RevisePriceAllowed
 * @property \DTS\eBaySDK\Trading\Types\StoreOwnerExtendedListingDurationsEnabledDefinitionType $StoreOwnerExtendedListingDurationsEnabled
 * @property \DTS\eBaySDK\Trading\Types\StoreOwnerExtendedListingDurationsDefinitionType $StoreOwnerExtendedListingDurations
 * @property \DTS\eBaySDK\Trading\Types\PaymentMethodDefinitionType $PaymentMethod
 * @property \DTS\eBaySDK\Trading\Types\Group1MaxFlatShippingCostDefinitionType $Group1MaxFlatShippingCost
 * @property \DTS\eBaySDK\Trading\Types\Group2MaxFlatShippingCostDefinitionType $Group2MaxFlatShippingCost
 * @property \DTS\eBaySDK\Trading\Types\Group3MaxFlatShippingCostDefinitionType $Group3MaxFlatShippingCost
 * @property \DTS\eBaySDK\Trading\Types\MaxFlatShippingCostCBTExemptDefinitionType $MaxFlatShippingCostCBTExempt
 * @property \DTS\eBaySDK\Trading\Types\MaxFlatShippingCostDefinitionType $MaxFlatShippingCost
 * @property \DTS\eBaySDK\Trading\Types\VariationsEnabledDefinitionType $VariationsEnabled
 * @property \DTS\eBaySDK\Trading\Types\FreeGalleryPlusEnabledDefinitionType $FreeGalleryPlusEnabled
 * @property \DTS\eBaySDK\Trading\Types\FreePicturePackEnabledDefinitionType $FreePicturePackEnabled
 * @property \DTS\eBaySDK\Trading\Types\ItemCompatibilityEnabledDefinitionType $ItemCompatibilityEnabled
 * @property \DTS\eBaySDK\Trading\Types\MaxItemCompatibilityDefinitionType $MaxItemCompatibility
 * @property \DTS\eBaySDK\Trading\Types\MinItemCompatibilityDefinitionType $MinItemCompatibility
 * @property \DTS\eBaySDK\Trading\Types\ConditionEnabledDefinitionType $ConditionEnabled
 * @property \DTS\eBaySDK\Trading\Types\ConditionValuesDefinitionType $ConditionValues
 * @property \DTS\eBaySDK\Trading\Types\ValueCategoryDefinitionType $ValueCategory
 * @property \DTS\eBaySDK\Trading\Types\ProductCreationEnabledDefinitionType $ProductCreationEnabled
 * @property \DTS\eBaySDK\Trading\Types\EANEnabledDefinitionType $EANEnabled
 * @property \DTS\eBaySDK\Trading\Types\ISBNEnabledDefinitionType $ISBNEnabled
 * @property \DTS\eBaySDK\Trading\Types\UPCEnabledDefinitionType $UPCEnabled
 * @property \DTS\eBaySDK\Trading\Types\CompatibleVehicleTypeDefinitionType $CompatibleVehicleType
 * @property \DTS\eBaySDK\Trading\Types\MaxGranularFitmentCountDefinitionType $MaxGranularFitmentCount
 * @property \DTS\eBaySDK\Trading\Types\ProfileCategoryGroupDefinitionType $ShippingProfileCategoryGroup
 * @property \DTS\eBaySDK\Trading\Types\ProfileCategoryGroupDefinitionType $PaymentProfileCategoryGroup
 * @property \DTS\eBaySDK\Trading\Types\ProfileCategoryGroupDefinitionType $ReturnPolicyProfileCategoryGroup
 * @property \DTS\eBaySDK\Trading\Types\VINSupportedDefinitionType $VINSupported
 * @property \DTS\eBaySDK\Trading\Types\VRMSupportedDefinitionType $VRMSupported
 * @property \DTS\eBaySDK\Trading\Types\SellerProvidedTitleSupportedDefinitionType $SellerProvidedTitleSupported
 * @property \DTS\eBaySDK\Trading\Types\DepositSupportedDefinitionType $DepositSupported
 * @property \DTS\eBaySDK\Trading\Types\GlobalShippingEnabledDefinitionType $GlobalShippingEnabled
 * @property \DTS\eBaySDK\Trading\Types\AdditionalCompatibilityEnabledDefinitionType $AdditionalCompatibilityEnabled
 * @property \DTS\eBaySDK\Trading\Types\PickupDropOffEnabledDefinitionType $PickupDropOffEnabled
 * @property \DTS\eBaySDK\Trading\Types\DigitalGoodDeliveryEnabledDefinitionType $DigitalGoodDeliveryEnabled
 * @property \DTS\eBaySDK\Trading\Types\EpidSupportedDefinitionType $EpidSupported
 * @property \DTS\eBaySDK\Trading\Types\KTypeSupportedDefinitionType $KTypeSupported
 * @property \DTS\eBaySDK\Trading\Types\ProductRequiredEnabledDefinitionType $ProductRequiredEnabled
 */
class FeatureDefinitionsType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ListingDurations' => [
            'type' => \DTS\eBaySDK\Trading\Types\ListingDurationDefinitionsType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ListingDurations'
        ],
        'ShippingTermsRequired' => [
            'type' => \DTS\eBaySDK\Trading\Types\ShippingTermRequiredDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingTermsRequired'
        ],
        'BestOfferEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\BestOfferEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferEnabled'
        ],
        'HomePageFeaturedEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\HomePageFeaturedEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HomePageFeaturedEnabled'
        ],
        'ProPackEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ProPackEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProPackEnabled'
        ],
        'ValuePackEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ValuePackEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ValuePackEnabled'
        ],
        'ProPackPlusEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ProPackPlusEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProPackPlusEnabled'
        ],
        'AdFormatEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\AdFormatEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdFormatEnabled'
        ],
        'BestOfferCounterEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\BestOfferCounterEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferCounterEnabled'
        ],
        'BestOfferAutoDeclineEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\BestOfferAutoDeclineEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferAutoDeclineEnabled'
        ],
        'LocalMarketSpecialitySubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketSpecialitySubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketSpecialitySubscription'
        ],
        'LocalMarketRegularSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketRegularSubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketRegularSubscription'
        ],
        'LocalMarketPremiumSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketPremiumSubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPremiumSubscription'
        ],
        'LocalMarketNonSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketNonSubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketNonSubscription'
        ],
        'MinimumReservePrice' => [
            'type' => \DTS\eBaySDK\Trading\Types\MinimumReservePriceDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MinimumReservePrice'
        ],
        'TransactionConfirmationRequestEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\TCREnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TransactionConfirmationRequestEnabled'
        ],
        'SellerContactDetailsEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\SellerContactDetailsEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerContactDetailsEnabled'
        ],
        'SkypeMeTransactionalEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\SkypeMeTransactionalEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SkypeMeTransactionalEnabled'
        ],
        'SkypeMeNonTransactionalEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\SkypeMeNonTransactionalEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SkypeMeNonTransactionalEnabled'
        ],
        'LocalListingDistancesRegular' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalListingDistancesRegularDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesRegular'
        ],
        'LocalListingDistancesSpecialty' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalListingDistancesSpecialtyDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesSpecialty'
        ],
        'LocalListingDistancesNonSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalListingDistancesNonSubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesNonSubscription'
        ],
        'ClassifiedAdPaymentMethodEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdPaymentMethodEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPaymentMethodEnabled'
        ],
        'ClassifiedAdShippingMethodEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdShippingMethodEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdShippingMethodEnabled'
        ],
        'ClassifiedAdBestOfferEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdBestOfferEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdBestOfferEnabled'
        ],
        'ClassifiedAdCounterOfferEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdCounterOfferEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdCounterOfferEnabled'
        ],
        'ClassifiedAdAutoDeclineEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdAutoDeclineEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdAutoDeclineEnabled'
        ],
        'ClassifiedAdContactByPhoneEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdContactByPhoneEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByPhoneEnabled'
        ],
        'ClassifiedAdContactByEmailEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdContactByEmailEnabledDefintionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByEmailEnabled'
        ],
        'SafePaymentRequired' => [
            'type' => \DTS\eBaySDK\Trading\Types\SafePaymentRequiredDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SafePaymentRequired'
        ],
        'ClassifiedAdPayPerLeadEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdPayPerLeadEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPayPerLeadEnabled'
        ],
        'ItemSpecificsEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ItemSpecificsEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemSpecificsEnabled'
        ],
        'PaisaPayFullEscrowEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\PaisaPayFullEscrowEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaisaPayFullEscrowEnabled'
        ],
        'BrandMPNIdentifierEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\BrandMPNIdentifierEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BrandMPNIdentifierEnabled'
        ],
        'BestOfferAutoAcceptEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\BestOfferAutoAcceptEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferAutoAcceptEnabled'
        ],
        'ClassifiedAdAutoAcceptEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdAutoAcceptEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdAutoAcceptEnabled'
        ],
        'CrossBorderTradeNorthAmericaEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\CrossBorderTradeNorthAmericaEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeNorthAmericaEnabled'
        ],
        'CrossBorderTradeGBEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\CrossBorderTradeGBEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeGBEnabled'
        ],
        'CrossBorderTradeAustraliaEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\CrossBorderTradeAustraliaEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeAustraliaEnabled'
        ],
        'PayPalBuyerProtectionEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\PayPalBuyerProtectionEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalBuyerProtectionEnabled'
        ],
        'BuyerGuaranteeEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\BuyerGuaranteeEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyerGuaranteeEnabled'
        ],
        'GalleryFeaturedDurations' => [
            'type' => \DTS\eBaySDK\Trading\Types\ListingEnhancementDurationDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GalleryFeaturedDurations'
        ],
        'INEscrowWorkflowTimeline' => [
            'type' => \DTS\eBaySDK\Trading\Types\INEscrowWorkflowTimelineDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'INEscrowWorkflowTimeline'
        ],
        'PayPalRequired' => [
            'type' => \DTS\eBaySDK\Trading\Types\PayPalRequiredDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalRequired'
        ],
        'eBayMotorsProAdFormatEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProAdFormatEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAdFormatEnabled'
        ],
        'eBayMotorsProContactByPhoneEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProContactByPhoneEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByPhoneEnabled'
        ],
        'eBayMotorsProPhoneCount' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProPhoneCountDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProPhoneCount'
        ],
        'eBayMotorsProContactByAddressEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProContactByAddressEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByAddressEnabled'
        ],
        'eBayMotorsProStreetCount' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProStreetCountDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProStreetCount'
        ],
        'eBayMotorsProCompanyNameEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProCompanyNameEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProCompanyNameEnabled'
        ],
        'eBayMotorsProContactByEmailEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProContactByEmailEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByEmailEnabled'
        ],
        'eBayMotorsProBestOfferEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProBestOfferEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProBestOfferEnabled'
        ],
        'eBayMotorsProAutoAcceptEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProAutoAcceptEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAutoAcceptEnabled'
        ],
        'eBayMotorsProAutoDeclineEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProAutoDeclineEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAutoDeclineEnabled'
        ],
        'eBayMotorsProPaymentMethodCheckOutEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProPaymentMethodCheckOutEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProPaymentMethodCheckOutEnabled'
        ],
        'eBayMotorsProShippingMethodEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProShippingMethodEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProShippingMethodEnabled'
        ],
        'eBayMotorsProCounterOfferEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProCounterOfferEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProCounterOfferEnabled'
        ],
        'eBayMotorsProSellerContactDetailsEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EBayMotorsProSellerContactDetailsEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProSellerContactDetailsEnabled'
        ],
        'LocalMarketAdFormatEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketAdFormatEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAdFormatEnabled'
        ],
        'LocalMarketContactByPhoneEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketContactByPhoneEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByPhoneEnabled'
        ],
        'LocalMarketPhoneCount' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketPhoneCountDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPhoneCount'
        ],
        'LocalMarketContactByAddressEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketContactByAddressEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByAddressEnabled'
        ],
        'LocalMarketStreetCount' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketStreetCountDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketStreetCount'
        ],
        'LocalMarketCompanyNameEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketCompanyNameEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketCompanyNameEnabled'
        ],
        'LocalMarketContactByEmailEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketContactByEmailEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByEmailEnabled'
        ],
        'LocalMarketBestOfferEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketBestOfferEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketBestOfferEnabled'
        ],
        'LocalMarketAutoAcceptEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketAutoAcceptEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAutoAcceptEnabled'
        ],
        'LocalMarketAutoDeclineEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketAutoDeclineEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAutoDeclineEnabled'
        ],
        'LocalMarketPaymentMethodCheckOutEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketPaymentMethodCheckOutEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPaymentMethodCheckOutEnabled'
        ],
        'LocalMarketShippingMethodEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketShippingMethodEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketShippingMethodEnabled'
        ],
        'LocalMarketCounterOfferEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketCounterOfferEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketCounterOfferEnabled'
        ],
        'LocalMarketSellerContactDetailsEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\LocalMarketSellerContactDetailsEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketSellerContactDetailsEnabled'
        ],
        'ClassifiedAdPhoneCount' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdPhoneCountDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPhoneCount'
        ],
        'ClassifiedAdContactByAddressEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdContactByAddressEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByAddressEnabled'
        ],
        'ClassifiedAdStreetCount' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdStreetCountDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdStreetCount'
        ],
        'ClassifiedAdCompanyNameEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ClassifiedAdCompanyNameEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdCompanyNameEnabled'
        ],
        'SpecialitySubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\SpecialitySubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SpecialitySubscription'
        ],
        'RegularSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\RegularSubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RegularSubscription'
        ],
        'PremiumSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\PremiumSubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PremiumSubscription'
        ],
        'NonSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\NonSubscriptionDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'NonSubscription'
        ],
        'ReturnPolicyEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ReturnPolicyEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyEnabled'
        ],
        'HandlingTimeEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\HandlingTimeEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HandlingTimeEnabled'
        ],
        'ReviseQuantityAllowed' => [
            'type' => \DTS\eBaySDK\Trading\Types\ReviseQuantityAllowedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReviseQuantityAllowed'
        ],
        'RevisePriceAllowed' => [
            'type' => \DTS\eBaySDK\Trading\Types\RevisePriceAllowedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RevisePriceAllowed'
        ],
        'StoreOwnerExtendedListingDurationsEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\StoreOwnerExtendedListingDurationsEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'StoreOwnerExtendedListingDurationsEnabled'
        ],
        'StoreOwnerExtendedListingDurations' => [
            'type' => \DTS\eBaySDK\Trading\Types\StoreOwnerExtendedListingDurationsDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'StoreOwnerExtendedListingDurations'
        ],
        'PaymentMethod' => [
            'type' => \DTS\eBaySDK\Trading\Types\PaymentMethodDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentMethod'
        ],
        'Group1MaxFlatShippingCost' => [
            'type' => \DTS\eBaySDK\Trading\Types\Group1MaxFlatShippingCostDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group1MaxFlatShippingCost'
        ],
        'Group2MaxFlatShippingCost' => [
            'type' => \DTS\eBaySDK\Trading\Types\Group2MaxFlatShippingCostDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group2MaxFlatShippingCost'
        ],
        'Group3MaxFlatShippingCost' => [
            'type' => \DTS\eBaySDK\Trading\Types\Group3MaxFlatShippingCostDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group3MaxFlatShippingCost'
        ],
        'MaxFlatShippingCostCBTExempt' => [
            'type' => \DTS\eBaySDK\Trading\Types\MaxFlatShippingCostCBTExemptDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxFlatShippingCostCBTExempt'
        ],
        'MaxFlatShippingCost' => [
            'type' => \DTS\eBaySDK\Trading\Types\MaxFlatShippingCostDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxFlatShippingCost'
        ],
        'VariationsEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\VariationsEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VariationsEnabled'
        ],
        'FreeGalleryPlusEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\FreeGalleryPlusEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FreeGalleryPlusEnabled'
        ],
        'FreePicturePackEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\FreePicturePackEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FreePicturePackEnabled'
        ],
        'ItemCompatibilityEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ItemCompatibilityEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemCompatibilityEnabled'
        ],
        'MaxItemCompatibility' => [
            'type' => \DTS\eBaySDK\Trading\Types\MaxItemCompatibilityDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxItemCompatibility'
        ],
        'MinItemCompatibility' => [
            'type' => \DTS\eBaySDK\Trading\Types\MinItemCompatibilityDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MinItemCompatibility'
        ],
        'ConditionEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ConditionEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConditionEnabled'
        ],
        'ConditionValues' => [
            'type' => \DTS\eBaySDK\Trading\Types\ConditionValuesDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConditionValues'
        ],
        'ValueCategory' => [
            'type' => \DTS\eBaySDK\Trading\Types\ValueCategoryDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ValueCategory'
        ],
        'ProductCreationEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ProductCreationEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProductCreationEnabled'
        ],
        'EANEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\EANEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EANEnabled'
        ],
        'ISBNEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ISBNEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ISBNEnabled'
        ],
        'UPCEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\UPCEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UPCEnabled'
        ],
        'CompatibleVehicleType' => [
            'type' => \DTS\eBaySDK\Trading\Types\CompatibleVehicleTypeDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CompatibleVehicleType'
        ],
        'MaxGranularFitmentCount' => [
            'type' => \DTS\eBaySDK\Trading\Types\MaxGranularFitmentCountDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxGranularFitmentCount'
        ],
        'ShippingProfileCategoryGroup' => [
            'type' => \DTS\eBaySDK\Trading\Types\ProfileCategoryGroupDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingProfileCategoryGroup'
        ],
        'PaymentProfileCategoryGroup' => [
            'type' => \DTS\eBaySDK\Trading\Types\ProfileCategoryGroupDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentProfileCategoryGroup'
        ],
        'ReturnPolicyProfileCategoryGroup' => [
            'type' => \DTS\eBaySDK\Trading\Types\ProfileCategoryGroupDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyProfileCategoryGroup'
        ],
        'VINSupported' => [
            'type' => \DTS\eBaySDK\Trading\Types\VINSupportedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VINSupported'
        ],
        'VRMSupported' => [
            'type' => \DTS\eBaySDK\Trading\Types\VRMSupportedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VRMSupported'
        ],
        'SellerProvidedTitleSupported' => [
            'type' => \DTS\eBaySDK\Trading\Types\SellerProvidedTitleSupportedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerProvidedTitleSupported'
        ],
        'DepositSupported' => [
            'type' => \DTS\eBaySDK\Trading\Types\DepositSupportedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DepositSupported'
        ],
        'GlobalShippingEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\GlobalShippingEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GlobalShippingEnabled'
        ],
        'AdditionalCompatibilityEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\AdditionalCompatibilityEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdditionalCompatibilityEnabled'
        ],
        'PickupDropOffEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\PickupDropOffEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PickupDropOffEnabled'
        ],
        'DigitalGoodDeliveryEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\DigitalGoodDeliveryEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DigitalGoodDeliveryEnabled'
        ],
        'EpidSupported' => [
            'type' => \DTS\eBaySDK\Trading\Types\EpidSupportedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EpidSupported'
        ],
        'KTypeSupported' => [
            'type' => \DTS\eBaySDK\Trading\Types\KTypeSupportedDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'KTypeSupported'
        ],
        'ProductRequiredEnabled' => [
            'type' => \DTS\eBaySDK\Trading\Types\ProductRequiredEnabledDefinitionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProductRequiredEnabled'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
