<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Types\MyMessagesSummaryType $Summary
 * @property \DTS\eBaySDK\Trading\Types\MyMessagesMessageArrayType $Messages
 */
class GetMyMessagesResponseType extends \DTS\eBaySDK\Trading\Types\AbstractResponseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'Summary' => [
            'type' => \DTS\eBaySDK\Trading\Types\MyMessagesSummaryType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Summary'
        ],
        'Messages' => [
            'type' => \DTS\eBaySDK\Trading\Types\MyMessagesMessageArrayType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Messages'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
