<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Types\OrderIDArrayType $OrderIDArray
 * @property \DateTime $CreateTimeFrom
 * @property \DateTime $CreateTimeTo
 * @property \DTS\eBaySDK\Trading\Enums\TradingRoleCodeType $OrderRole
 * @property \DTS\eBaySDK\Trading\Enums\OrderStatusCodeType $OrderStatus
 * @property \DTS\eBaySDK\Trading\Enums\ListingTypeCodeType $ListingType
 * @property \DTS\eBaySDK\Trading\Types\PaginationType $Pagination
 * @property \DateTime $ModTimeFrom
 * @property \DateTime $ModTimeTo
 * @property integer $NumberOfDays
 * @property boolean $IncludeFinalValueFee
 * @property \DTS\eBaySDK\Trading\Enums\SortOrderCodeType $SortingOrder
 */
class GetOrdersRequestType extends \DTS\eBaySDK\Trading\Types\AbstractRequestType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'OrderIDArray' => [
            'type' => \DTS\eBaySDK\Trading\Types\OrderIDArrayType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'OrderIDArray'
        ],
        'CreateTimeFrom' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CreateTimeFrom'
        ],
        'CreateTimeTo' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CreateTimeTo'
        ],
        'OrderRole' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'OrderRole'
        ],
        'OrderStatus' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'OrderStatus'
        ],
        'ListingType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ListingType'
        ],
        'Pagination' => [
            'type' => \DTS\eBaySDK\Trading\Types\PaginationType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Pagination'
        ],
        'ModTimeFrom' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ModTimeFrom'
        ],
        'ModTimeTo' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ModTimeTo'
        ],
        'NumberOfDays' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'NumberOfDays'
        ],
        'IncludeFinalValueFee' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'IncludeFinalValueFee'
        ],
        'SortingOrder' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SortingOrder'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(self::class, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[self::class] = 'GetOrdersRequest';
        }

        $this->setValues(self::class, $childValues);
    }
}
