<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Types\SMSSubscriptionType $SMSSubscription
 * @property \DTS\eBaySDK\Trading\Types\SummaryEventScheduleType[] $SummarySchedule
 * @property string $ExternalUserData
 */
class NotificationUserDataType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'SMSSubscription' => [
            'type' => \DTS\eBaySDK\Trading\Types\SMSSubscriptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SMSSubscription'
        ],
        'SummarySchedule' => [
            'type' => \DTS\eBaySDK\Trading\Types\SummaryEventScheduleType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'SummarySchedule'
        ],
        'ExternalUserData' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ExternalUserData'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
