<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Enums\PaymentTransactionStatusCodeType $PaymentStatus
 * @property \DTS\eBaySDK\Trading\Types\UserIdentityType $Payer
 * @property \DTS\eBaySDK\Trading\Types\UserIdentityType $Payee
 * @property \DateTime $PaymentTime
 * @property \DTS\eBaySDK\Trading\Types\AmountType $PaymentAmount
 * @property \DTS\eBaySDK\Trading\Types\TransactionReferenceType $ReferenceID
 * @property \DTS\eBaySDK\Trading\Types\AmountType $FeeOrCreditAmount
 * @property \DTS\eBaySDK\Trading\Types\TransactionReferenceType[] $PaymentReferenceID
 */
class PaymentTransactionType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'PaymentStatus' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentStatus'
        ],
        'Payer' => [
            'type' => \DTS\eBaySDK\Trading\Types\UserIdentityType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Payer'
        ],
        'Payee' => [
            'type' => \DTS\eBaySDK\Trading\Types\UserIdentityType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Payee'
        ],
        'PaymentTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentTime'
        ],
        'PaymentAmount' => [
            'type' => \DTS\eBaySDK\Trading\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentAmount'
        ],
        'ReferenceID' => [
            'type' => \DTS\eBaySDK\Trading\Types\TransactionReferenceType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReferenceID'
        ],
        'FeeOrCreditAmount' => [
            'type' => \DTS\eBaySDK\Trading\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FeeOrCreditAmount'
        ],
        'PaymentReferenceID' => [
            'type' => \DTS\eBaySDK\Trading\Types\TransactionReferenceType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'PaymentReferenceID'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
