<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Types\OfferType $Offer
 * @property string $ItemID
 * @property boolean $BlockOnWarning
 * @property \DTS\eBaySDK\Trading\Types\AffiliateTrackingDetailsType $AffiliateTrackingDetails
 * @property \DTS\eBaySDK\Trading\Types\NameValueListArrayType $VariationSpecifics
 */
class PlaceOfferRequestType extends \DTS\eBaySDK\Trading\Types\AbstractRequestType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'Offer' => [
            'type' => \DTS\eBaySDK\Trading\Types\OfferType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Offer'
        ],
        'ItemID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemID'
        ],
        'BlockOnWarning' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BlockOnWarning'
        ],
        'AffiliateTrackingDetails' => [
            'type' => \DTS\eBaySDK\Trading\Types\AffiliateTrackingDetailsType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AffiliateTrackingDetails'
        ],
        'VariationSpecifics' => [
            'type' => \DTS\eBaySDK\Trading\Types\NameValueListArrayType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VariationSpecifics'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(self::class, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[self::class] = 'PlaceOfferRequest';
        }

        $this->setValues(self::class, $childValues);
    }
}
