<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Types\RefundDetailsType[] $Refund
 * @property \DTS\eBaySDK\Trading\Types\ReturnsWithinDetailsType[] $ReturnsWithin
 * @property \DTS\eBaySDK\Trading\Types\ReturnsAcceptedDetailsType[] $ReturnsAccepted
 * @property boolean $Description
 * @property \DTS\eBaySDK\Trading\Types\WarrantyOfferedDetailsType[] $WarrantyOffered
 * @property \DTS\eBaySDK\Trading\Types\WarrantyTypeDetailsType[] $WarrantyType
 * @property \DTS\eBaySDK\Trading\Types\WarrantyDurationDetailsType[] $WarrantyDuration
 * @property boolean $EAN
 * @property \DTS\eBaySDK\Trading\Types\ShippingCostPaidByDetailsType[] $ShippingCostPaidBy
 * @property \DTS\eBaySDK\Trading\Types\RestockingFeeValueDetailsType[] $RestockingFeeValue
 * @property string $DetailVersion
 * @property \DateTime $UpdateTime
 */
class ReturnPolicyDetailsType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'Refund' => [
            'type' => \DTS\eBaySDK\Trading\Types\RefundDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'Refund'
        ],
        'ReturnsWithin' => [
            'type' => \DTS\eBaySDK\Trading\Types\ReturnsWithinDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReturnsWithin'
        ],
        'ReturnsAccepted' => [
            'type' => \DTS\eBaySDK\Trading\Types\ReturnsAcceptedDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReturnsAccepted'
        ],
        'Description' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Description'
        ],
        'WarrantyOffered' => [
            'type' => \DTS\eBaySDK\Trading\Types\WarrantyOfferedDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'WarrantyOffered'
        ],
        'WarrantyType' => [
            'type' => \DTS\eBaySDK\Trading\Types\WarrantyTypeDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'WarrantyType'
        ],
        'WarrantyDuration' => [
            'type' => \DTS\eBaySDK\Trading\Types\WarrantyDurationDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'WarrantyDuration'
        ],
        'EAN' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EAN'
        ],
        'ShippingCostPaidBy' => [
            'type' => \DTS\eBaySDK\Trading\Types\ShippingCostPaidByDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ShippingCostPaidBy'
        ],
        'RestockingFeeValue' => [
            'type' => \DTS\eBaySDK\Trading\Types\RestockingFeeValueDetailsType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RestockingFeeValue'
        ],
        'DetailVersion' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DetailVersion'
        ],
        'UpdateTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UpdateTime'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
