<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property integer $ColorSchemeID
 * @property string $Name
 * @property \DTS\eBaySDK\Trading\Types\StoreColorType $Color
 * @property \DTS\eBaySDK\Trading\Types\StoreFontType $Font
 */
class StoreColorSchemeType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ColorSchemeID' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ColorSchemeID'
        ],
        'Name' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Name'
        ],
        'Color' => [
            'type' => \DTS\eBaySDK\Trading\Types\StoreColorType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Color'
        ],
        'Font' => [
            'type' => \DTS\eBaySDK\Trading\Types\StoreFontType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Font'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
