<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Order\Types;

/**
 *
 * @property \DTS\eBaySDK\Order\Types\CreditCard $creditCard
 * @property \DTS\eBaySDK\Order\Types\LineItemInput[] $lineItemInputs
 * @property \DTS\eBaySDK\Order\Types\ShippingAddress $shippingAddress
 */
class CreateSignInCheckoutSessionRequest extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'creditCard' => [
            'type' => \DTS\eBaySDK\Order\Types\CreditCard::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'creditCard'
        ],
        'lineItemInputs' => [
            'type' => \DTS\eBaySDK\Order\Types\LineItemInput::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'lineItemInputs'
        ],
        'shippingAddress' => [
            'type' => \DTS\eBaySDK\Order\Types\ShippingAddress::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingAddress'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        $this->setValues(self::class, $childValues);
    }
}
