<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ReturnManagement\Types;

/**
 *
 * @property \DTS\eBaySDK\ReturnManagement\Types\ItemFilterType $itemFilter
 * @property string $orderId
 * @property \DTS\eBaySDK\ReturnManagement\Types\DateRangeFilterType $creationDateRangeFilter
 * @property \DTS\eBaySDK\ReturnManagement\Types\ReturnStatusFilterType $ReturnStatusFilter
 * @property \DTS\eBaySDK\ReturnManagement\Types\UserFilterType $otherUserFilter
 * @property \DTS\eBaySDK\ReturnManagement\Types\PaginationInput $paginationInput
 * @property \DTS\eBaySDK\ReturnManagement\Enums\ReturnSortType $sortType
 * @property \DTS\eBaySDK\ReturnManagement\Enums\ReturnSortOrderType $sortOrderType
 */
class GetUserReturnsRequest extends \DTS\eBaySDK\ReturnManagement\Types\BaseRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'itemFilter' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\ItemFilterType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'itemFilter'
        ],
        'orderId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'orderId'
        ],
        'creationDateRangeFilter' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\DateRangeFilterType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'creationDateRangeFilter'
        ],
        'ReturnStatusFilter' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\ReturnStatusFilterType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnStatusFilter'
        ],
        'otherUserFilter' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\UserFilterType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'otherUserFilter'
        ],
        'paginationInput' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\PaginationInput::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paginationInput'
        ],
        'sortType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'sortType'
        ],
        'sortOrderType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'sortOrderType'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/returns/v1/services"';
        }

        if (!array_key_exists(self::class, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[self::class] = 'getUserReturnsRequest';
        }

        $this->setValues(self::class, $childValues);
    }
}
