<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ReturnManagement\Types;

/**
 *
 * @property string $globalId
 * @property \DTS\eBaySDK\ReturnManagement\Types\ReturnResponseHistoryType[] $returnHistory
 * @property \DTS\eBaySDK\ReturnManagement\Types\RefundInfoType $refundInfo
 * @property \DTS\eBaySDK\ReturnManagement\Types\ReturnPolicyInfoType $returnPolicy
 * @property \DTS\eBaySDK\ReturnManagement\Types\ShipmentType $buyerReturnShipment
 * @property \DTS\eBaySDK\ReturnManagement\Types\ShipmentType[] $shipmentInfo
 * @property \DTS\eBaySDK\ReturnManagement\Types\CaseIdType $caseId
 */
class ReturnDetailType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'globalId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'globalId'
        ],
        'returnHistory' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\ReturnResponseHistoryType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'returnHistory'
        ],
        'refundInfo' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\RefundInfoType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'refundInfo'
        ],
        'returnPolicy' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\ReturnPolicyInfoType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnPolicy'
        ],
        'buyerReturnShipment' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\ShipmentType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'buyerReturnShipment'
        ],
        'shipmentInfo' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\ShipmentType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'shipmentInfo'
        ],
        'caseId' => [
            'type' => \DTS\eBaySDK\ReturnManagement\Types\CaseIdType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'caseId'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/returns/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
