<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Marketing\Types;

use DTS\eBaySDK\Marketing\Types\BulkDeleteAdsByInventoryReferenceRestResponse;

class BulkDeleteAdsByInventoryReferenceRestResponseTest extends \PHPUnit\Framework\TestCase
{
    private $obj;

    protected function setUp(): void
    {
        $this->obj = new BulkDeleteAdsByInventoryReferenceRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf(\DTS\eBaySDK\Marketing\Types\BulkDeleteAdsByInventoryReferenceRestResponse::class, $this->obj);
    }

    public function testExtendsBulkDeleteAdsByInventoryReferenceResponse()
    {
        $this->assertInstanceOf(\DTS\eBaySDK\Marketing\Types\BulkDeleteAdsByInventoryReferenceResponse::class, $this->obj);
    }
}
