<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Analytics\Types;

/**
 *
 * @property string $endDate
 * @property \DTS\eBaySDK\Analytics\Types\Header $header
 * @property string $lastUpdatedDate
 * @property \DTS\eBaySDK\Analytics\Types\Record[] $records
 * @property string $startDate
 * @property \DTS\eBaySDK\Analytics\Types\ErrorDetailV3[] $warnings
 */
class Report extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'endDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'endDate'
        ],
        'header' => [
            'type' => \DTS\eBaySDK\Analytics\Types\Header::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'header'
        ],
        'lastUpdatedDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'lastUpdatedDate'
        ],
        'records' => [
            'type' => \DTS\eBaySDK\Analytics\Types\Record::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'records'
        ],
        'startDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'startDate'
        ],
        'warnings' => [
            'type' => \DTS\eBaySDK\Analytics\Types\ErrorDetailV3::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'warnings'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        $this->setValues(self::class, $childValues);
    }
}
