<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finding\Types;

/**
 *
 * @property \DTS\eBaySDK\Finding\Types\Amount $currentPrice
 * @property \DTS\eBaySDK\Finding\Types\Amount $convertedCurrentPrice
 * @property integer $bidCount
 * @property string $sellingState
 * @property string $timeLeft
 */
class SellingStatus extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'currentPrice' => [
            'type' => \DTS\eBaySDK\Finding\Types\Amount::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'currentPrice'
        ],
        'convertedCurrentPrice' => [
            'type' => \DTS\eBaySDK\Finding\Types\Amount::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'convertedCurrentPrice'
        ],
        'bidCount' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'bidCount'
        ],
        'sellingState' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'sellingState'
        ],
        'timeLeft' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'timeLeft'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/search/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
