<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\FileTransfer\Types;

/**
 *
 * @property string $taskReferenceId
 * @property string $fileReferenceId
 * @property string $fileFormat
 * @property \DTS\eBaySDK\FileTransfer\Types\FileAttachment $fileAttachment
 */
class UploadFileRequest extends \DTS\eBaySDK\FileTransfer\Types\BaseServiceRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'taskReferenceId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'taskReferenceId'
        ],
        'fileReferenceId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'fileReferenceId'
        ],
        'fileFormat' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'fileFormat'
        ],
        'fileAttachment' => [
            'type' => \DTS\eBaySDK\FileTransfer\Types\FileAttachment::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'fileAttachment'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/services"';
        }

        if (!array_key_exists(self::class, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[self::class] = 'uploadFileRequest';
        }

        $this->setValues(self::class, $childValues);
    }
}
