<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ProductMetadata\Types;

/**
 *
 * @property string $categoryId
 * @property \DTS\eBaySDK\ProductMetadata\Types\PropertyValue[] $propertyFilter
 * @property boolean $listFormatOnly
 * @property \DTS\eBaySDK\ProductMetadata\Types\SortOrder[] $sortOrder
 */
class GetProductSearchValuesBaseRequest extends \DTS\eBaySDK\ProductMetadata\Types\BaseServiceRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'categoryId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'categoryId'
        ],
        'propertyFilter' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\PropertyValue::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'propertyFilter'
        ],
        'listFormatOnly' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'listFormatOnly'
        ],
        'sortOrder' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\SortOrder::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'sortOrder'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
