<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ProductMetadata\Types;

/**
 *
 * @property string $propertyName
 * @property \DTS\eBaySDK\ProductMetadata\Types\Value $value
 * @property \DTS\eBaySDK\ProductMetadata\Types\PropertyNameValue[] $childPropertyNameValue
 */
class PropertyNameValue extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'propertyName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'propertyName'
        ],
        'value' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\Value::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'value'
        ],
        'childPropertyNameValue' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\PropertyNameValue::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'childPropertyNameValue'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
