<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ProductMetadata\Types;

/**
 *
 * @property \DTS\eBaySDK\ProductMetadata\Types\URITypeSpecificInformation $uriTypeSpecificInformation
 * @property \DTS\eBaySDK\ProductMetadata\Types\NumericTypeSpecificInformation $numericTypeSpecificInformation
 * @property \DTS\eBaySDK\ProductMetadata\Types\MediaTypeSpecificInformation $mediaTypeSpecificInformation
 * @property \DTS\eBaySDK\ProductMetadata\Types\StringTypeSpecificInformation $stringTypeSpecificInformation
 */
class TypeSpecificInformation extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'uriTypeSpecificInformation' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\URITypeSpecificInformation::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'uriTypeSpecificInformation'
        ],
        'numericTypeSpecificInformation' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\NumericTypeSpecificInformation::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'numericTypeSpecificInformation'
        ],
        'mediaTypeSpecificInformation' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\MediaTypeSpecificInformation::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'mediaTypeSpecificInformation'
        ],
        'stringTypeSpecificInformation' => [
            'type' => \DTS\eBaySDK\ProductMetadata\Types\StringTypeSpecificInformation::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'stringTypeSpecificInformation'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/marketplacecatalog/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
