<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\RelatedItemsManagement\Types;

/**
 *
 * @property \DTS\eBaySDK\RelatedItemsManagement\Enums\AckValue $ack
 * @property \DTS\eBaySDK\RelatedItemsManagement\Types\ErrorMessage $errorMessage
 * @property string $version
 * @property \DateTime $timestamp
 * @property \DTS\eBaySDK\RelatedItemsManagement\Types\ExtensionType[] $extension
 */
class BaseResponse extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ack' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ack'
        ],
        'errorMessage' => [
            'type' => \DTS\eBaySDK\RelatedItemsManagement\Types\ErrorMessage::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'errorMessage'
        ],
        'version' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'version'
        ],
        'timestamp' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'timestamp'
        ],
        'extension' => [
            'type' => \DTS\eBaySDK\RelatedItemsManagement\Types\ExtensionType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'extension'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/sellerinventory/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
