<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Types;

/**
 *
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionOptionType $offerOtherSolution
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoOptionType $provideTrackingInfo
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundOptionType $issueFullRefund
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundOptionType $issuePartialRefund
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoOptionType $provideShippingInfo
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\RequestBuyerToReturnOptionType $requestBuyerToReturn
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingOrTrackingInfoOptionType $provideShippingOrTrackingInfo
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoOptionType $provideRefundInfo
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\ContactCustomerSupportOptionType $contactCustomerSupport
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportOptionType $escalateToCustomerSupport
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportOptionType $appealToCustomerSupport
 */
class ActivityOptionListType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'offerOtherSolution' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'offerOtherSolution'
        ],
        'provideTrackingInfo' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'provideTrackingInfo'
        ],
        'issueFullRefund' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'issueFullRefund'
        ],
        'issuePartialRefund' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'issuePartialRefund'
        ],
        'provideShippingInfo' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'provideShippingInfo'
        ],
        'requestBuyerToReturn' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\RequestBuyerToReturnOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'requestBuyerToReturn'
        ],
        'provideShippingOrTrackingInfo' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingOrTrackingInfoOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'provideShippingOrTrackingInfo'
        ],
        'provideRefundInfo' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'provideRefundInfo'
        ],
        'contactCustomerSupport' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\ContactCustomerSupportOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'contactCustomerSupport'
        ],
        'escalateToCustomerSupport' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'escalateToCustomerSupport'
        ],
        'appealToCustomerSupport' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportOptionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'appealToCustomerSupport'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/resolution/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
