<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Types;

/**
 *
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\AppealRef $appealRef
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\MoneyMovementRef $moneyMovementRef
 * @property string $onholdReason
 * @property \DTS\eBaySDK\ResolutionCaseManagement\Types\OnHoldReasonDetailType $onholdReasonDetail
 */
class ResponseHistoryAttributesType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'appealRef' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\AppealRef::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'appealRef'
        ],
        'moneyMovementRef' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\MoneyMovementRef::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'moneyMovementRef'
        ],
        'onholdReason' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'onholdReason'
        ],
        'onholdReasonDetail' => [
            'type' => \DTS\eBaySDK\ResolutionCaseManagement\Types\OnHoldReasonDetailType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'onholdReasonDetail'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/resolution/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
