<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Types;

/**
 *
 * @property \DTS\eBaySDK\PostOrder\Types\CustomListDataType[] $listData
 * @property integer $listId
 * @property string $listName
 * @property \DTS\eBaySDK\PostOrder\Types\CustomListType $listType
 */
class CustomListDetailType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'listData' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\CustomListDataType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'listData'
        ],
        'listId' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'listId'
        ],
        'listName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'listName'
        ],
        'listType' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\CustomListType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'listType'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        $this->setValues(self::class, $childValues);
    }
}
