<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Types;

/**
 *
 * @property boolean $eligible
 * @property \DTS\eBaySDK\PostOrder\Types\DateTime $endTime
 * @property \DTS\eBaySDK\PostOrder\Types\DateTime $startTime
 */
class EscalationEligibilityInfo extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'eligible' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eligible'
        ],
        'endTime' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\DateTime::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'endTime'
        ],
        'startTime' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\DateTime::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'startTime'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        $this->setValues(self::class, $childValues);
    }
}
