<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Types;

/**
 *
 * @property \DTS\eBaySDK\PostOrder\Types\InquirySummaryType[] $members
 * @property \DTS\eBaySDK\PostOrder\Types\PaginationOutput $paginationOutput
 * @property integer $totalNumberOfInquiries
 */
class InquirySearchResponse extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'members' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\InquirySummaryType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'members'
        ],
        'paginationOutput' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\PaginationOutput::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paginationOutput'
        ],
        'totalNumberOfInquiries' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'totalNumberOfInquiries'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        $this->setValues(self::class, $childValues);
    }
}
