<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Types;

/**
 *
 * @property \DTS\eBaySDK\PostOrder\Types\RuleModificationType $operation
 * @property \DTS\eBaySDK\PostOrder\Types\PriorityListType $priorityList
 * @property \DTS\eBaySDK\PostOrder\Types\RuleDetailInputType $ruleDetail
 * @property integer $versionId
 */
class ModifyDispositionRuleRequest extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'operation' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\RuleModificationType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'operation'
        ],
        'priorityList' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\PriorityListType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'priorityList'
        ],
        'ruleDetail' => [
            'type' => \DTS\eBaySDK\PostOrder\Types\RuleDetailInputType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ruleDetail'
        ],
        'versionId' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'versionId'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        $this->setValues(self::class, $childValues);
    }
}
