<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\BulkDataExchange\Types;

/**
 *
 * @property string $UUID
 * @property \DTS\eBaySDK\BulkDataExchange\Types\DownloadJobRecurringFilter $downloadJobRecurringFilter
 * @property integer $frequencyInMinutes
 * @property string $downloadJobType
 * @property \DTS\eBaySDK\BulkDataExchange\Types\MonthlyRecurrence $monthlyRecurrence
 * @property \DTS\eBaySDK\BulkDataExchange\Types\WeeklyRecurrence $weeklyRecurrence
 * @property \DTS\eBaySDK\BulkDataExchange\Types\DailyRecurrence $dailyRecurrence
 */
class CreateRecurringJobRequest extends \DTS\eBaySDK\BulkDataExchange\Types\BaseServiceRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'UUID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UUID'
        ],
        'downloadJobRecurringFilter' => [
            'type' => \DTS\eBaySDK\BulkDataExchange\Types\DownloadJobRecurringFilter::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'downloadJobRecurringFilter'
        ],
        'frequencyInMinutes' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'frequencyInMinutes'
        ],
        'downloadJobType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'downloadJobType'
        ],
        'monthlyRecurrence' => [
            'type' => \DTS\eBaySDK\BulkDataExchange\Types\MonthlyRecurrence::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'monthlyRecurrence'
        ],
        'weeklyRecurrence' => [
            'type' => \DTS\eBaySDK\BulkDataExchange\Types\WeeklyRecurrence::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'weeklyRecurrence'
        ],
        'dailyRecurrence' => [
            'type' => \DTS\eBaySDK\BulkDataExchange\Types\DailyRecurrence::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'dailyRecurrence'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/services"';
        }

        if (!array_key_exists(self::class, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[self::class] = 'createRecurringJobRequest';
        }

        $this->setValues(self::class, $childValues);
    }
}
