<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\BulkDataExchange\Types;

/**
 *
 * @property \DTS\eBaySDK\BulkDataExchange\Types\GetItemJobActionType $jobAction
 * @property \DTS\eBaySDK\BulkDataExchange\Enums\ItemEventType $filterType
 * @property boolean $includeAttributes
 * @property boolean $includeDescription
 * @property \DateTime $reportDateFrom
 * @property \DateTime $reportDateTo
 * @property string[] $timeFrame
 * @property string[] $changedFieldSelector
 */
class GetItemInfoReportFilter extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'jobAction' => [
            'type' => \DTS\eBaySDK\BulkDataExchange\Types\GetItemJobActionType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'jobAction'
        ],
        'filterType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'filterType'
        ],
        'includeAttributes' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'includeAttributes'
        ],
        'includeDescription' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'includeDescription'
        ],
        'reportDateFrom' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'reportDateFrom'
        ],
        'reportDateTo' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'reportDateTo'
        ],
        'timeFrame' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'timeFrame'
        ],
        'changedFieldSelector' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'changedFieldSelector'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
