<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\BulkDataExchange\Types;

/**
 *
 * @property \DateTime $creationTimeFrom
 * @property \DateTime $creationTimeTo
 * @property string[] $jobType
 * @property \DTS\eBaySDK\BulkDataExchange\Enums\JobStatus[] $jobStatus
 */
class GetJobsRequest extends \DTS\eBaySDK\BulkDataExchange\Types\BaseServiceRequest
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'creationTimeFrom' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'creationTimeFrom'
        ],
        'creationTimeTo' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'creationTimeTo'
        ],
        'jobType' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'jobType'
        ],
        'jobStatus' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'jobStatus'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/services"';
        }

        if (!array_key_exists(self::class, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[self::class] = 'getJobsRequest';
        }

        $this->setValues(self::class, $childValues);
    }
}
