<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Types;

/**
 *
 * @property \DTS\eBaySDK\MerchantData\Types\PaymentInformationType $Payments
 * @property \DTS\eBaySDK\MerchantData\Types\RefundInformationType $Refunds
 */
class PaymentsInformationType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'Payments' => [
            'type' => \DTS\eBaySDK\MerchantData\Types\PaymentInformationType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Payments'
        ],
        'Refunds' => [
            'type' => \DTS\eBaySDK\MerchantData\Types\RefundInformationType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Refunds'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
