<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Types;

/**
 *
 * @property \DTS\eBaySDK\MerchantData\Types\AmountType $RefundFromSeller
 * @property \DTS\eBaySDK\MerchantData\Types\AmountType $TotalRefundToBuyer
 * @property \DateTime $RefundTime
 * @property string $RefundID
 * @property \DTS\eBaySDK\MerchantData\Types\AmountType $RefundAmount
 */
class RefundType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'RefundFromSeller' => [
            'type' => \DTS\eBaySDK\MerchantData\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RefundFromSeller'
        ],
        'TotalRefundToBuyer' => [
            'type' => \DTS\eBaySDK\MerchantData\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TotalRefundToBuyer'
        ],
        'RefundTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RefundTime'
        ],
        'RefundID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RefundID'
        ],
        'RefundAmount' => [
            'type' => \DTS\eBaySDK\MerchantData\Types\AmountType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RefundAmount'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
