<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Types;

/**
 *
 * @property string $PictureName
 * @property \DTS\eBaySDK\MerchantData\Enums\PictureSetCodeType $PictureSet
 * @property \DTS\eBaySDK\MerchantData\Enums\PictureFormatCodeType $PictureFormat
 * @property string $FullURL
 * @property string $BaseURL
 * @property \DTS\eBaySDK\MerchantData\Types\PictureSetMemberType[] $PictureSetMember
 * @property string $ExternalPictureURL
 * @property \DateTime $UseByDate
 */
class SiteHostedPictureDetailsType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'PictureName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PictureName'
        ],
        'PictureSet' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PictureSet'
        ],
        'PictureFormat' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PictureFormat'
        ],
        'FullURL' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FullURL'
        ],
        'BaseURL' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BaseURL'
        ],
        'PictureSetMember' => [
            'type' => \DTS\eBaySDK\MerchantData\Types\PictureSetMemberType::class,
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'PictureSetMember'
        ],
        'ExternalPictureURL' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ExternalPictureURL'
        ],
        'UseByDate' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UseByDate'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(self::class, $childValues);
    }
}
