<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Types;

/**
 *
 * @property integer $PictureSystemVersion
 * @property \DTS\eBaySDK\MerchantData\Types\SiteHostedPictureDetailsType $SiteHostedPictureDetails
 */
class UploadSiteHostedPicturesResponseType extends \DTS\eBaySDK\MerchantData\Types\AbstractResponseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'PictureSystemVersion' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PictureSystemVersion'
        ],
        'SiteHostedPictureDetails' => [
            'type' => \DTS\eBaySDK\MerchantData\Types\SiteHostedPictureDetailsType::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SiteHostedPictureDetails'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(self::class, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[self::class] = 'UploadSiteHostedPicturesResponse';
        }

        $this->setValues(self::class, $childValues);
    }
}
