<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\BusinessPoliciesManagement\Types;

/**
 *
 * @property \DTS\eBaySDK\BusinessPoliciesManagement\Types\PaymentProfile $paymentProfile
 * @property \DTS\eBaySDK\BusinessPoliciesManagement\Types\ReturnPolicyProfile $returnPolicyProfile
 * @property \DTS\eBaySDK\BusinessPoliciesManagement\Types\ShippingPolicyProfile $shippingPolicyProfile
 */
class SetSellerProfileResponse extends \DTS\eBaySDK\BusinessPoliciesManagement\Types\BaseResponse
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'paymentProfile' => [
            'type' => \DTS\eBaySDK\BusinessPoliciesManagement\Types\PaymentProfile::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'paymentProfile'
        ],
        'returnPolicyProfile' => [
            'type' => \DTS\eBaySDK\BusinessPoliciesManagement\Types\ReturnPolicyProfile::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnPolicyProfile'
        ],
        'shippingPolicyProfile' => [
            'type' => \DTS\eBaySDK\BusinessPoliciesManagement\Types\ShippingPolicyProfile::class,
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingPolicyProfile'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(self::class, self::$properties)) {
            self::$properties[self::class] = array_merge(self::$properties[parent::class], self::$propertyTypes);
        }

        if (!array_key_exists(self::class, self::$xmlNamespaces)) {
            self::$xmlNamespaces[self::class] = 'xmlns="http://www.ebay.com/marketplace/selling/v1/services"';
        }

        $this->setValues(self::class, $childValues);
    }
}
